spring:
  application:
    name: purchase-order

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  threads:
    virtual:
      enabled: true

  data:
    web:
      pageable:
        one-indexed-parameters: true